---
title: "README"
author: "AI"
date: "12 February 2022"
output: 
  html_document:
    keep_md: TRUE

---


### README  



This assignment is the final project and submission for the Getting and Cleaning Data Coursera course.  

The folder contains the main source code for the analysis named  run_analysis.R.  

It does the following as required by the course:
You should create one R script called run_analysis.R that does the following. 

1. Merges the training and the test sets to create one data set.  
2. Extracts only the measurements on the mean and standard deviation for each measurement.   
3. Uses descriptive activity names to name the activities in the data set  
4. Appropriately labels the data set with descriptive variable names. 
5. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.



codebook.md contains a description of the operational code and each step of the formation of the final tidy data file, along with data table dimensions.

